package com.mappo.data.repository

import com.mappo.data.db.OverlayElementDao
import com.mappo.data.model.OverlayElement
import com.mappo.data.model.RemapTarget
import com.mappo.data.model.tapRemapTarget
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.test.runTest
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test

/**
 * Repository is a thin wrapper over the DAO; tests use a hand-rolled fake DAO
 * (the DAO is an interface, so no MockK or Robolectric needed). Mirrors
 * [AppProfileBindingRepositoryTest]'s style.
 */
class OverlayRepositoryTest {

    private lateinit var dao: FakeOverlayElementDao
    private lateinit var subject: OverlayRepository

    @Before
    fun setUp() {
        dao = FakeOverlayElementDao()
        subject = OverlayRepository(dao)
    }

    private fun element(
        id: Long = 0,
        layoutId: Long = 1L,
        label: String = "",
        zIndex: Int = 0,
        tapTarget: String = RemapTarget.Unbound.encode(),
    ) = OverlayElement(
        id = id,
        layoutId = layoutId,
        label = label,
        x = 0.1f, y = 0.2f, width = 0.15f, height = 0.15f,
        tapTarget = tapTarget,
        zIndex = zIndex,
    )

    @Test
    fun add_persistsElementWithAssignedId() = runTest {
        val newId = subject.add(element(label = "A"))
        assertEquals("A", subject.getById(newId)?.label)
    }

    @Test
    fun elementsByProfile_filtersToProfile_andOrdersByZIndex() = runTest {
        subject.add(element(layoutId = 1L, label = "front", zIndex = 5))
        subject.add(element(layoutId = 1L, label = "back", zIndex = 1))
        subject.add(element(layoutId = 2L, label = "other", zIndex = 0))

        val p1 = subject.elementsByProfile(1L).first()
        assertEquals(listOf("back", "front"), p1.map { it.label })
    }

    @Test
    fun update_replacesExistingRow() = runTest {
        val id = subject.add(element(label = "old"))
        val stored = subject.getById(id)!!
        subject.update(stored.copy(label = "new", x = 0.5f))

        val reloaded = subject.getById(id)!!
        assertEquals("new", reloaded.label)
        assertEquals(0.5f, reloaded.x)
    }

    @Test
    fun delete_removesElement() = runTest {
        val id = subject.add(element())
        subject.deleteById(id)
        assertNull(subject.getById(id))
    }

    @Test
    fun clearForLayout_removesOnlyThatLayout() = runTest {
        subject.add(element(layoutId = 1L))
        subject.add(element(layoutId = 1L))
        subject.add(element(layoutId = 2L))

        subject.clearForLayout(1L)

        assertTrue(subject.elementsByProfileOnce(1L).isEmpty())
        assertEquals(1, subject.elementsByProfileOnce(2L).size)
    }

    @Test
    fun tapRemapTarget_decodesStoredBinding() = runTest {
        val id = subject.add(element(tapTarget = RemapTarget.Keyboard("ENTER").encode()))
        assertEquals(RemapTarget.Keyboard("ENTER"), subject.getById(id)!!.tapRemapTarget)
    }
}

/**
 * In-memory [OverlayElementDao] keyed by autogenerated id. Backs Flow queries with a
 * StateFlow so collectors observe updates after insert/update/delete.
 */
private class FakeOverlayElementDao : OverlayElementDao {
    private val rows = MutableStateFlow<Map<Long, OverlayElement>>(emptyMap())
    private var nextId = 1L

    private fun sorted(elements: Collection<OverlayElement>) =
        elements.sortedWith(compareBy({ it.zIndex }, { it.id }))

    override fun getByLayout(layoutId: Long): Flow<List<OverlayElement>> =
        rows.map { sorted(it.values.filter { row -> row.layoutId == layoutId }) }

    override suspend fun getByLayoutOnce(layoutId: Long): List<OverlayElement> =
        sorted(rows.value.values.filter { it.layoutId == layoutId })

    override fun getBySet(actionSetId: Long): Flow<List<OverlayElement>> =
        rows.map { sorted(it.values.filter { row -> row.actionSetId == actionSetId }) }

    override fun getByLayer(actionLayerId: Long): Flow<List<OverlayElement>> =
        rows.map { sorted(it.values.filter { row -> row.actionLayerId == actionLayerId }) }

    override suspend fun getBySetOnce(actionSetId: Long): List<OverlayElement> =
        sorted(rows.value.values.filter { it.actionSetId == actionSetId })

    override suspend fun getByLayerOnce(actionLayerId: Long): List<OverlayElement> =
        sorted(rows.value.values.filter { it.actionLayerId == actionLayerId })

    override suspend fun getById(id: Long): OverlayElement? = rows.value[id]

    override suspend fun insert(element: OverlayElement): Long {
        val id = if (element.id == 0L) nextId++ else element.id
        rows.value = rows.value + (id to element.copy(id = id))
        return id
    }

    override suspend fun insertAll(elements: List<OverlayElement>): List<Long> =
        elements.map { insert(it) }

    override suspend fun update(element: OverlayElement) {
        if (rows.value.containsKey(element.id)) {
            rows.value = rows.value + (element.id to element)
        }
    }

    override suspend fun update(elements: List<OverlayElement>) {
        // Single atomic state swap, mirroring Room's one-transaction / one-emission semantics.
        rows.value = rows.value + elements
            .filter { rows.value.containsKey(it.id) }
            .associateBy { it.id }
    }

    override suspend fun delete(element: OverlayElement) {
        rows.value = rows.value - element.id
    }

    override suspend fun deleteById(id: Long) {
        rows.value = rows.value - id
    }

    override suspend fun deleteAllForLayout(layoutId: Long) {
        rows.value = rows.value.filterValues { it.layoutId != layoutId }
    }
}
