package com.mappo.data.db

import android.content.Context
import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import com.mappo.data.model.Layout
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.test.runTest
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(AndroidJUnit4::class)
class LayoutEntityDaoTest {

    private lateinit var db: AppDatabase
    private lateinit var dao: LayoutDao

    @Before
    fun setUp() {
        val ctx = ApplicationProvider.getApplicationContext<Context>()
        db = Room.inMemoryDatabaseBuilder(ctx, AppDatabase::class.java)
            .allowMainThreadQueries()
            .build()
        dao = db.layoutDao()
    }

    @After
    fun tearDown() {
        db.close()
    }

    @Test
    fun insert_assignsAutoGeneratedId() = runTest {
        val id = dao.insert(Layout(name = "Test"))
        assertTrue("auto-generated id should be > 0", id > 0)
    }

    @Test
    fun getById_returnsInserted() = runTest {
        val id = dao.insert(Layout(name = "Test"))
        assertEquals(Layout(id = id, name = "Test"), dao.getById(id))
    }

    @Test
    fun getById_missing_returnsNull() = runTest {
        assertNull(dao.getById(9999L))
    }

    @Test
    fun getAll_emitsAlphabeticallyOrdered() = runTest {
        dao.insert(Layout(name = "Charlie"))
        dao.insert(Layout(name = "Alpha"))
        dao.insert(Layout(name = "Bravo"))

        val names = dao.getAll().first().map { it.name }
        assertEquals(listOf("Alpha", "Bravo", "Charlie"), names)
    }

    @Test
    fun delete_removesProfile() = runTest {
        val id = dao.insert(Layout(name = "ToDelete"))
        val layout = dao.getById(id)!!
        dao.delete(layout)
        assertNull(dao.getById(id))
    }
}
